#!/bin/sh

# -----------------------------------------------------------------------------
# xinitrc
# Description: Config file for startx
# -----------------------------------------------------------------------------
# Location: $HOME/.xinitrc
# -----------------------------------------------------------------------------

# Source {{{
# -----------------------------------------------------------------------------
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# xresources
[ -r "$XDG_CONFIG_HOME/X11/xresources" ] && xrdb -merge -I"$XDG_CONFIG_HOME/X11" "$XDG_CONFIG_HOME/X11/xresources"
# -----------------------------------------------------------------------------
# }}}

# Fonts {{{
# -----------------------------------------------------------------------------
xset +fp /usr/share/fonts/misc/
xset +fp /usr/share/fonts/TTF/
xset +fp /usr/share/fonts/OTF/
xset +fp /usr/share/fonts/local/
xset fp rehash
# -----------------------------------------------------------------------------
# }}}

# Display {{{
# -----------------------------------------------------------------------------
# terminal
if [ -x "$(which urxvtd 2> /dev/null)" ]; then
    urxvtd -q -f -o
fi

# wallpaper
if [ -x "$(which nitrogen 2> /dev/null)" ]; then
    nitrogen --restore &
fi

# screen powersave
xset +dpms
xset dpms 0 0 300

#calibrate display
if [ -x "$(which redshift 2> /dev/null)" ] && [ -n "$XDG_CONFIG_HOME" ] && [ -r "$XDG_CONFIG_HOME/redshift/redshift.conf" ]; then
    redshift -c "$XDG_CONFIG_HOME/redshift/redshift.conf" &
fi
# -----------------------------------------------------------------------------
# }}}

# Sound {{{
# -----------------------------------------------------------------------------
# mpd
if [ -x "$(which mpd 2> /dev/null)" ]; then
    mpd &
fi
# -----------------------------------------------------------------------------
# }}}

# Input {{{
# -----------------------------------------------------------------------------
# keyboard
xset r rate 200 35

# mouse
xsetroot -cursor_name 'left_ptr'
if [ -x "$(which unclutter 2> /dev/null)" ]; then
    unclutter &
fi

# hotkeys
if [ -x "$(which sxhkd 2> /dev/null)" ]; then
    sxhkd &
fi
# -----------------------------------------------------------------------------
# }}}

# Window Manager {{{
# -----------------------------------------------------------------------------
if [ -x "$(which bspwm 2> /dev/null)" ]; then
    exec bspwm
fi
# -----------------------------------------------------------------------------
# }}}

# vim:foldmethod=marker:foldlevel=0
