#! /bin/sh

if [ $(pgrep -f "dzen2 -title-name notifications"*) >/dev/null ]; then
    pkill -f "dzen2 -title-name notifications"* && bspc config right_padding 0;
else
    bspc config right_padding 600 && \
        dzen2 -title-name notifications -p -ta c -h 1620 -w 600 -geometry -600+90 -fn 'Source Code Pro:size=12' -e 'onstart=lower' & disown;
fi
