#! /bin/sh

# -----------------------------------------------------------------------------
# bspwmrc
# Description: Config file for bspwm
# -----------------------------------------------------------------------------
# Location: $HOME/.config/bspwm/bspwmrc
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# => General
# -----------------------------------------------------------------------------
# {{{
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle  false
# }}}

# -----------------------------------------------------------------------------
# => Appearance
# -----------------------------------------------------------------------------
# {{{
bspc config border_width          5
bspc config window_gap            40
bspc config top_padding           40
bspc config bottom_padding        0
bspc config focused_border_color  "#458588"
bspc config normal_border_color   "#1d2121"
bspc config presel_feedback_color "#a89984"
# }}}

# -----------------------------------------------------------------------------
# => Rules
# -----------------------------------------------------------------------------
# {{{
# albumart
bspc rule -a "Sxiv:mpd_album_art" state=floating border=off manage=off focus=off
bspc rule -a "Sxiv:sxivg_image" state=floating
# }}}

# -----------------------------------------------------------------------------
# => Monitors
# -----------------------------------------------------------------------------
# {{{
bspc monitor -d 1 2 3 4 5
# }}}

# -----------------------------------------------------------------------------
# => Panels
# -----------------------------------------------------------------------------
# {{{
# music, clock, and battery
$HOME/.dotfiles/bin/wm/menu_bar/menu_bar &
# }}}

# vim:foldmethod=marker:foldlevel=0
