#! /bin/sh

# -----------------------------------------------------------------------------
# bspwmrc
# Description: Config file for bspwm
# -----------------------------------------------------------------------------
# Location: $HOME/.config/bspwm/bspwmrc
# -----------------------------------------------------------------------------

bspc config border_width         5
bspc config window_gap           50
bspc config top_padding          40
bspc config bottom_padding       40

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true

bspc config focused_border_color "#5e8d87"
bspc config normal_border_color  "#1d1f21"

bspc rule -a "mpd_album_art" floating=on border=off manage=false

bspc monitor -d 1 2 3 4 5 6 7

bash $HOME/.dotfiles/bspwm/panel &
