#! /bin/sh

# -----------------------------------------------------------------------------
# bspwmrc
# Description: Config file for bspwm
# -----------------------------------------------------------------------------
# Location: $HOME/.config/bspwm/bspwmrc
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# => General
# -----------------------------------------------------------------------------
# {{{
bspc monitor -d 1 2 3 4 5
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle  false
# }}}

# -----------------------------------------------------------------------------
# => Appearance
# -----------------------------------------------------------------------------
# {{{
bspc config border_width          5
bspc config window_gap            40
bspc config top_padding           40
bspc config bottom_padding        0
bspc config focused_border_color  "#d79921"
bspc config normal_border_color   "#928374"
bspc config presel_feedback_color "#928374"
# }}}

# -----------------------------------------------------------------------------
# => Panels
# -----------------------------------------------------------------------------
# {{{
# music, clock, and battery
$HOME/.dotfiles/bin/ui/menu_bar/menu_bar &
# }}}

# vim:foldmethod=marker:foldlevel=0
