#! /bin/sh

# -----------------------------------------------------------------------------
# panel
# Description: Starts music, clock and battery panels
# -----------------------------------------------------------------------------
# Location: $HOME/.config/bspwm/panel
# -----------------------------------------------------------------------------

$HOME/.dotfiles/bin/panels/music &
$HOME/.dotfiles/bin/panels/clock &
$HOME/.dotfiles/bin/panels/battery &
