#! /bin/sh

# -----------------------------------------------------------------------------
# bspwmrc
# Description: Config file for bspwm
# -----------------------------------------------------------------------------
# Location: $HOME/.config/bspwm/bspwmrc
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# => General
# -----------------------------------------------------------------------------
# {{{
# desktops 1-5 on monitor 1; desktops 6-10 on monitor 2
bspc monitor 'eDP-1' -n "1" -d 1 2 3 4 5

# default presel ratio
bspc config split_ratio 0.50

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
# }}}

# -----------------------------------------------------------------------------
# => Appearance
# -----------------------------------------------------------------------------
# {{{
# border width in pixels
bspc config border_width 5
# node not focused on any monitor
bspc config normal_border_color "#928374"
# focused node on inactive monitor
bspc config active_border_color "#689d6a"
# focused node on active monitor
bspc config focused_border_color "#d79921"

# presel color
bspc config presel_feedback_color "#928374"

# per monitor spacing in pixels
bspc config -m 1 window_gap 40
bspc config -m 1 top_padding 40

# layout spacing
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config paddingless_monocle false
# }}}

# -----------------------------------------------------------------------------
# => Panels
# -----------------------------------------------------------------------------
# {{{
# music, clock, and battery
$HOME/.bin/ui/menu_bar/menu_bar &
# }}}

# vim:foldmethod=marker:foldlevel=0
