#! /bin/sh

# -----------------------------------------------------------------------------
# Description: Config file for bspwm
# Location: $XDG_CONFIG_HOME/bspwm/bspwmrc
# -----------------------------------------------------------------------------

# General {{{
# -----------------------------------------------------------------------------
# default monitor
bspc monitor -d 1 2 3 4 5
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# global layout settings
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle false

# global presel ratio
bspc config split_ratio 0.50

# default monitor spacing in pixels
bspc config window_gap 12

# Border width in pixels
bspc config border_width 2
# }}}

# Colors {{{
# -----------------------------------------------------------------------------
# Source colors
. "$HOME/.local/bin/colors"
# Node not focused on any monitor
bspc config normal_border_color   "${color7}"
# Focused node on active monitor
bspc config focused_border_color  "${color8}"
# Focused node on inactive monitor
bspc config active_border_color   "${color8}"
# Presel color
bspc config presel_feedback_color "${color8}"
# -----------------------------------------------------------------------------
# }}}

# vim:foldmethod=marker:foldlevel=0
