#! /bin/sh

# -----------------------------------------------------------------------------
# bspwmrc
# Description: Config file for bspwm
# -----------------------------------------------------------------------------
# Location: $HOME/.config/bspwm/bspwmrc
# -----------------------------------------------------------------------------

# General {{{
# -----------------------------------------------------------------------------
# default monitor
bspc monitor 'eDP-1' -n "1" -d 1 2 3 4 5
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# global layout settings
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle false

# global presel ratio
bspc config split_ratio 0.50

# default monitor spacing in pixels
bspc config -m 1 window_gap 40

# Border width in pixels
bspc config border_width 5

# Node not focused on any monitor
bspc config normal_border_color "#928374"
# Focused node on active monitor
bspc config focused_border_color "#d79921"
# Focused node on inactive monitor
bspc config active_border_color "#689d6a"
# Presel color
bspc config presel_feedback_color "#928374"
# -----------------------------------------------------------------------------
# }}}

# vim:foldmethod=marker:foldlevel=0
