[[ $OSTYPE == darwin* && -f $HOME/.dotfiles/zsh/darwin/zlogout ]] && source $HOME/.dotfiles/zsh/darwin/zlogout
[[ $OSTYPE == linux*  && -f $HOME/.dotfiles/zsh/linux/zlogout  ]] && source $HOME/.dotfiles/zsh/linux/zlogout
