# -----------------------------------------------------------------------------
# zprofile
# Description: This file is generally used for automatic execution of user's
#   scripts at login.
# -----------------------------------------------------------------------------
# Location: $HOME/.zprofile
# -----------------------------------------------------------------------------

[[ $OSTYPE == darwin* && -f $HOME/.dotfiles/zsh/darwin/zprofile ]] && source $HOME/.dotfiles/zsh/darwin/zprofile
[[ $OSTYPE == linux*  && -f $HOME/.dotfiles/zsh/linux/zprofile  ]] && source $HOME/.dotfiles/zsh/linux/zprofile
